const express = require('express')
const movieRouter = require('./routes/movie')
const cors = require('cors')
const reviewRouter = require('./routes/review')
const signInRouter = require('./routes/login')
const signUpRouter = require('./routes/signup')
const allRouter = require('./routes/getAll')
const editProfileRouter = require('./routes/editProfile')
const changePasswordRouter = require('./routes/changePassword')
const app = express()

app.use(cors())
app.use(express.json())
app.use("/movie", movieRouter)
app.use("/review", reviewRouter)
app.use("/", allRouter)
app.use("/", signInRouter)
app.use("/", signUpRouter)
app.use("/", editProfileRouter)
app.use("/", changePasswordRouter)

app.listen(4000, "0.0.0.0", () => {
    console.log("@--------MovieReviews--------@")
})